### Create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "krepe512@gmail.com",
    "password": "trash"
}

### Simple test
http://localhost:3000/auth/test



### sign in
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "krepe504@gmail.com",
    "password": "trash"
}

### sign out
POST  http://localhost:3000/auth/signout


### Find by id
GET http://localhost:3000/auth/2

### Find by who
GET http://localhost:3000/auth/who

### Find all users with the given email
GET http://localhost:3000/auth?email=mymail@gmail.com

### Delete user

DELETE http://localhost:3000/auth/1

### Patch

PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password" : "engine"
}


### Set color
GET http://localhost:3000/auth/colors/pizza

### Get color
GET http://localhost:3000/auth/colors
